# Generated by Django 5.0.6 on 2024-06-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='incident_types',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='PredictionHistory',
        ),
    ]
